[package]
name = "rustz"
version = "0.1.0"
authors = ["Joshua Gould <joshua.gould@homeadvisor.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
